Repository dnd-side-project/dnd-12th-2-iOS, pull requests merged in 2025-03, with the labels that each got.

#43 [REFACTOR] #42 - Auth API Refactoring
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/AuthClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Navigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Login/LoginNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Login/LoginView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/MyPage/MyPage.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/dnd_12th_2_iOSApp.swift
Labels: REFACTOR, API

#54 [REFACTOR] #48, #53, #52 - Goal/Plan API Refactoring, FirstGoalFlow
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/GoalClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/GuideClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDFloatingButton.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/Goal.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/Guide.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/Plan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Navigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/GoalAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/GuideAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/DTO/GoalReqDto.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/DTO/GuideResponseDto.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Goal/FirstGoalFlow.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Goal/FirstGoalView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Goal/GoalCompleteView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Goal/GoalView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Goal/MakeGoal.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Home/Calendar/CalendarView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Home/HomeNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Home/HomeView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Login/LoginNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Login/LoginView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Onboarding/Onboarding.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Onboarding/OnboardingCompleteView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Onboarding/OnboardingView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Question/QuestionForm.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Question/Questionnaire.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Utils/Extensions/Date+.swift
Labels: REFACTOR, API

#59 [REFACTOR] #46 - GoalAPI Refactoring
  dnd-12th-2-iOS/dnd-12th-2-iOS.xcodeproj/project.pbxproj
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/Color/customBackground.colorset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLight.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLight.imageset/ic_bulb@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLight.imageset/ic_bulb@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLight.imageset/iconLight.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/placeholderImage.imageset/Frame 2087327143@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/placeholderImage.imageset/Frame 2087327143@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/placeholderImage.imageset/placeholderImage.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/placeholderImageSmall.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/placeholderImageSmall.imageset/Frame 2087327143@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/placeholderImageSmall.imageset/Frame 2087327143@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/placeholderImageSmall.imageset/placeholderImageSmall.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/GoalClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDFloatingButton.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDNavigationView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDResultRow.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/TipBubble.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/Goal.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/GoalInfo.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/Plan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/GoalAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/DTO/GoalResonseDto.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/DTO/PlanResponseDto.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/DTO/StatisticsResponseDto.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Calendar/CalendarView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Calendar/MakeCalendar.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Goal/FetchGoal.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Goal/GoalList.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/MainNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/MainView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/FetchPlan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/PlanListView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/dnd_12th_2_iOSApp.swift
Labels: REFACTOR, API

#61 [FIX] #60 - Onboarding API 변경사항 대응
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/UserClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/Plan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/DTO/UserOnboardingResDto.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Login/LoginNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Splash/LoginCheck.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/dnd_12th_2_iOSApp.swift
Labels: FIX, API

#65 [FIX] #64 - 날짜가 그룹별로 묶이지 않는 문제
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/goalIcon.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/goalIcon.imageset/Mountain flag.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/goalIcon.imageset/Mountain flag@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/goalIcon.imageset/Mountain flag@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconGray.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconGray.imageset/_@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconGray.imageset/_@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconGray.imageset/iconGray.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/trashIcon.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/trashIcon.imageset/Delete.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/trashIcon.imageset/Delete@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/trashIcon.imageset/Delete@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDBottomSheet.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/FetchPlan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/PlanListView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Utils/Extensions/Date+.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Utils/Manager/HapticManager.swift
Labels: FIX

#79 [FIX] #78 - 디자인 QA 반영
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconTextField.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconTextField.imageset/Frame 2085666763@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconTextField.imageset/Frame 2085666763@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconTextField.imageset/iconTextField.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDDatePicker.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDResultRow.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDRoundTextField.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/FetchGoal/GoalList.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/FetchGoal/GoalListCell.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/PlanListView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/SetGoal/GoalResultView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/SetGoal/SetGoalFlowView.swift
Labels: FIX

#80 [FEAT] #76 - 목표삭제 기능 추가
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/GoalClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/GoalAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/MainNavigation.swift
Labels: FEAT

#81 [FEAT] #77 - 계획 삭제 API 연동
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/PlanClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/PlanAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Calendar/MakeCalendar.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/FetchPlan.swift
Labels: FEAT

#85 [FEAT] 애플로그인 회원탈퇴
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/AuthClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Navigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/AuthAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/MyPage/MyPage.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/MyPage/MyPageView.swift
Labels: FEAT, API

#86 [FEAT] 할 일 개선 기능 구현
  dnd-12th-2-iOS/dnd-12th-2-iOS.xcodeproj/project.pbxproj
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/Color/pink100.colorset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/GoalClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDResultRow.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/GoalAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackComplete.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackResult.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackResultView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FetchFeedback.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/MainNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/MainView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/ImprovePlan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Plan/ImprovePlanView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/SetGoal/FetchTip/FetchTip.swift
Labels: FEAT, API

#87 [FIX] #83 - 피드백 완료시 결과 변경된 API 대응
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackFail.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackFail.imageset/X@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackFail.imageset/X@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackFail.imageset/iconFeedbackFail.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackSuccess.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackSuccess.imageset/X@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackSuccess.imageset/X@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconFeedbackSuccess.imageset/iconFeedbackSuccess.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconHistory.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconHistory.imageset/Frame 2085666764@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconHistory.imageset/Frame 2085666764@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconHistory.imageset/iconHistory.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLine.imageset/Contents.json
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLine.imageset/Line 1@2x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLine.imageset/Line 1@3x.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Assets.xcassets/iconLine.imageset/iconLine.png
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/PlanClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/ResultPlan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/CompleteList.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackResult.swift
Labels: FIX, API

#93 [FEAT] #91 - 피드백 상세 API 연동
  dnd-12th-2-iOS/dnd-12th-2-iOS.xcodeproj/project.pbxproj
  dnd-12th-2-iOS/dnd-12th-2-iOS/Client/PlanClient.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/DesignSystem/UIComponent/DDResultRow.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/Plan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Model/ResultPlan.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/API/PlanAPI.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/DTO/PlanCompleteResDto.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Network/Mapper/PlanMapper.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/CompleteList.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackDetail.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackDetailView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackResult.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FeedbackResultView.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Feedback/FetchFeedback.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/Home/HomeNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/MainNavigation.swift
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Main/MainView.swift
Labels: FEAT, API

#95 [FIX] #94 - 로그인화면 Image가 잘리는 문제 수정
  dnd-12th-2-iOS/dnd-12th-2-iOS.xcodeproj/project.pbxproj
  dnd-12th-2-iOS/dnd-12th-2-iOS/Presentation/Login/LoginView.swift
Labels: FIX
